Update nginx.sh to remove if Statement
hassio-addons/addon-bookstack pull request #76
Opened 2021-04-21 23:23 UTC by ajesseperez

# Proposed Changes
Remove if statement on the nginx.sh script to allow nginx Config to include port 80 even if host port is not specified in the addon config. This will allow proxing from other services like NGINX to connect via internal docker network even if the host port is not specified.

I have confirmed that changes allow for internal docker network routing and host port is reachable if specified

2021-04-21 23:51 UTC, sinclairpaul commented
So this would allow someone to configure the addon with no external port, just to allow internal routing?

2021-04-22 02:17 UTC, ajesseperez commented
Yes, because with the removed if statement it would only create the nginx server for port 80 if the addon config specified a host port. Without the if statement (and no host port on the addon), the nginx script creates it regardless but it is not mapped to a host port. Anything in the "hassio" docker network can hit that port. For your reference I am using the following configuration with the "core_nginx_proxy" addon to validate. Please note that the configuration option customize.active on core_nginx_proxy must be set to `true` to use this configuration.


File Location: /share/nginx_proxy/bookstack.conf
```
server {
    server_name [YOUR DOMAIN HERE];
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_certificate /ssl/fullchain.pem;
    ssl_certificate_key /ssl/privkey.pem;
    # dhparams file
    ssl_dhparam /data/dhparams.pem;
    listen 443 ssl http2;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    proxy_buffering off;
    include /share/nginx_proxy_default*.conf;
    location / {
        proxy_pass http://a0d7b954-bookstack;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

2021-04-22 12:54 UTC, sinclairpaul commented
I understand your use case and reasoning, I do however think we should write a warning if null, as the WebUI link will fail (although that is the same behavior as today)

2021-04-22 20:31 UTC, ajesseperez commented
@sinclairpaul I have just updated the Docs for the addon :D

2021-04-22 20:41 UTC, sinclairpaul requested changes
Can we add something like:
```
if bashio::var.is_empty "$(bashio::addon.port 80)"; then
    bashio::log.warning "No host port is configured, please ensure a port is set for external access to function"
fi
```

Also I would prefer it not to be in the docs directly, we can remove that.

2021-04-22 21:12 UTC, ajesseperez commented
Gotcha! Just wiped out the Doc Changes and updated the script to include those changes. I wasn't aware of the functionality of bashio. That is really cool! Thanks :D

2021-04-22 21:13 UTC, sinclairpaul approved these changes

2021-04-22 21:18 UTC, merged

2021-04-22 21:18 UTC, sinclairpaul commented
Thanks @ajesseperez